### ISSUE TITLE
Dependency Issues when Attempting to Evaluate Baseline Model

### ISSUE THREAD

**Issue by PatrickKollman** [felixgontier/dcase-2022-baseline#1]
Im currently trying to evaluate the baseline model, but running into dependency issues when I run "main.py".

Namely, I cannot import "load_yaml_file" in the line "utils.file_io import load_yaml_file" in "main.py".

And it seems there is no "eval_metrics.py" in the repository either, which raises an issue in "metrics.py".

We're these files/directories meant to be included in the repository or are there separate packages that need to be installed?

Thanks

**Comment by felixgontier** [comment]
Hi,

I have added the missing YAML loading utilities.

The "eval_metrics.py" file is part of the caption evaluation repository, which should be extracted in the baseline root directory as per the Repository Setup section of the readme:
https://github.com/audio-captioning/caption-evaluation-tools

Let me know if this fixes your issues running the baseline.
