### ISSUE TITLE
Pre-trained BART

### ISSUE THREAD

**Issue by XinhaoMei** [felixgontier/dcase-2022-baseline#3]
Hi, thanks for your great work.
I am wondering the baseline results in DCASE page were obtained with a pre-trained BART or not?

**Comment by felixgontier** [comment]
Hi,
No, the published baseline results are obtained with a randomly initialized transformer, only the tokenizer is pre-trained.
This is to encourage modifying hyper-parameters without the rigidity that comes with pre-trained weights. 

Using a pre-trained BART checkpoint is still an option with the lm/pretrained setting if you want to experiment on this.
I do not have results with pre-training for this specific architecture/conditioning configuration, however from our [DCASE2021 paper](https://dcase.community/documents/workshop2021/proceedings/DCASE2021Workshop_Gontier_57.pdf) pre-training should moderately increase captioning performance.

**Comment by XinhaoMei** [comment]
Got it. Thank you so much for your quick reply!
